services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: khai
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - movix_network

  app:
    build: .
    ports:
      - "5000:5000"

    env_file:
      - ./.env

    command: sh -c "npx prisma migrate dev && npm run prisma:seed && npm run start"
    depends_on:
      - db
    networks:
      - movix_network
    volumes:
      - ./prisma:/app/prisma

volumes:
  db_data:

networks:
  movix_network:
    driver: bridge